# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Heroku Action
      # You may pin to the exact commit or the version.
      # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
      uses: CDNievas/heroku-action@v1.0
      with:
        # Used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.HEROKU_API_TOKEN }}
        # Email from Heroku Account
        heroku_email: "nsalmadi@colby.edu"
        # The appname to use for deploying/updating
        heroku_app_name: ${{ secrets.HEROKI_APP_NAME }}
        # The branch that you would like to deploy to Heroku
        branch: # optional, default is HEAD
        # Set this to true if want to use --force
        useforce: # optional
        # Set if your app is located in a subdirectory.
        appdir: # optional, default is 
        # Contents of the Procfile to save and deploy
        procfile: # optional, default is 
        # Set to true if you need upload files generated dynamically by the GitHub Action to Heroku
        dynamicFiles: # optional
        # Buildpacks to install on Heroku
        buildpacks: # optional, default is 
        # Path to an localized env file
        env_file: # optional, default is 
